Fix Arena#isPlayer NullPointerException
com.destroystokyo.paper.exception.ServerSchedulerException: Task #587232 for BedWars2023 v2.0.0-SNAPSHOT generated an exception
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1680)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1269)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:311)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.contains(Object)" because "this.players" is null
	at BedWars2023.jar//com.tomkeuper.bedwars.arena.Arena.isPlayer(Arena.java:1647)
	at BedWars2023.jar//com.tomkeuper.bedwars.arena.Arena.lambda$addPlayer$8(Arena.java:619)
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78)
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474)
	... 5 more