Fix for:
com.destroystokyo.paper.exception.ServerSchedulerException: Task #959268 for BedWars2023 v2.0.0-SNAPSHOT generated an exception
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1680)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1269)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:311)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassCastException: class org.bukkit.craftbukkit.block.data.CraftBlockData cannot be cast to class org.bukkit.block.data.type.Ladder (org.bukkit.craftbukkit.block.data.CraftBlockData and org.bukkit.block.data.type.Ladder are in unnamed module of loader java.net.URLClassLoader @7591083d)
	at BedWars2023.jar//com.tomkeuper.bedwars.support.version.v1_21_R5.v1_21_R5.placeLadder(v1_21_R5.java:734)
	at BedWars2023.jar//com.tomkeuper.bedwars.popuptower.NewPlaceBlock.<init>(NewPlaceBlock.java:57)
	at BedWars2023.jar//com.tomkeuper.bedwars.popuptower.TowerWest.lambda$new$0(TowerWest.java:167)
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78)
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474)
	... 5 more

probably blocks are outside of world bounds, in which case we don't want stuff breaking and exceptions flying...